### ISSUE TITLE
No need to announce failed write when a job has been canceled.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#165] opened 2020-06-15 14:35 UTC
In this interesting scenario, an order was canceled on 6 June 2020 (see [L264R5EDA](https://cardshop.hotspot.kiwix.org/orders/L264R5EDA).

Exactly one week later, the user and order owner got a `write_failed` message . Since they had already received a cancellation email on June 6, this second email is largely unwarranted.

It's not exactly a bug, but I would suggest that in case a job is canceled the whole thing be canceled rather than left lying around until it expires and incorrectly notifies of an error.

**Comment by Popolechien** [comment] 2021-04-22 12:38
duplicate of #72¨

**Comment by Popolechien** [comment] 2021-04-22 14:24
Hmmm maybe not exactly a duplicate in fact. #72 asks for two different notifications, this one simply wants the job entirely deleted.

**Comment by rgaudin** [comment] 2021-04-22 14:27
It's a duplicate of #237 I think. We mark it canceled in the manager but never request actual cancellation. Let's tackle it there.

**Closed by rgaudin** 2021-04-22 14:27 UTC
Labels: enhancement
