### ISSUE TITLE
Delete file from physical writer once SD card creation was completed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#155] opened 2020-03-27 12:03 UTC
I've had the scenario where I created several cards in a row, and allocation to one of the two writers seemed kind of random. Then out of nowhere the last creation (32Gb) took about a week before I got the invite to insert an SD card (vs. a couple of hours normally; I don't think it was due to suddendly low bandwidth).

I suspect that the writer waits for the usual end-of-life date to delete the files that were uploaded to the warehouse irrespective of the fact that they've been flashed or not. This in turns creates an artificial queue.

**Comment by Popolechien** [comment] 2020-04-28 07:33
Updating this to `bug` - the last creation took ten days before I got notified that I could insert a card. Ended up re-creating the image, downloading it and flashing it directly from my computer.

**Comment by kelson42** [comment] 2020-04-28 07:51
@rgaudin Seems quite serious to me if we are stuck for days waiting to a notification to write the card.

**Comment by rgaudin** [comment] 2020-04-28 08:22
Can you send order numbers please? I remember we discussed it but I'd like to check actual reasons for this and put that in the ticket.

**Comment by Popolechien** [comment] 2020-04-28 08:24
@rgaudin #5e8c66f5455 is the latest one.

**Comment by rgaudin** [comment] 2020-04-28 09:02
Thank you very much!

I looked at the download folder and there was 600GB of space used by failed task. So the remaining space was less than 200GB.

Here's a recap of all files and the issues leading to them not being deleted.

| File | Issue |
| --- | --- |
|  93G Jan 21 17:53 5e271d7b98c8bf54e53f1990.img | #159 |
|  92G Apr  6 08:38 5e8abe2d98c8bf00233d9562.img | #86 |
|  92G Apr 28 03:59 5e8c66f598c8bf00233dc455.img | #86 |
|  77G Mar  6 18:44 5e62722898c8bf54e2413c33.img | ? |
|  70G Jan 24 19:56 5e2b1de398c8bf54e23c9ad8.img | #86 |
|  64G Oct 28  2019 5db53cef98c8bf7187a0625e.img | #86 |
|  50G Jan 22 15:40 5e284d4498c8bf54e23c5d02.img | #159 |
|  37G Jan 22 07:27 5e27db7a98c8bf54e53f318d.img | #159 |
|  28G Mar 17 10:54 5e70999c98c8bf00223a8905.img | #86 |
|  28G Mar 17 16:33 5e70e6b798c8bf00223a8fca.img | `downloaded_failed_to_remove` (code) |
|  28G Mar 25 12:54 5e737fc098c8bf00223ac6e8.img | #86 |
| 9.4G Jan 15 08:26 5e1ec17398c8bf54e23b8d1b.img | #159 |

So it's mostly our old #86 bug and a #159 one that I just opened. Strangely, [5e62722](https://cardshop.hotspot.kiwix.org/all-orders/5e62722898c8bf54e2413c33) left its image behind while being completely successful. It's unexpected as the line reporting `pending_image_removal` is right before the one removing the image and should that one failed, we should have received a `downloaded_failed_to_remove` one.

I have manually removed all those files so it should be OK now.

I will close this issue as it's not reflecting the actual cause and the causes are now covered in the other issue.

**Closed by rgaudin** 2020-04-28 09:02 UTC
Labels: bug
