### ISSUE TITLE
Physical writer gets mixed up between slots

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#259] opened 2021-05-18 09:35 UTC
I created order [60a2bd5298c8bf00224eab28](https://cardshop.hotspot.kiwix.org/orders/f/60a2bd5298c8bf00224eab28) and got the email asking me to insert my SD card into **slot B**
![Capture d’écran 2021-05-18 à 11 33 05](https://user-images.githubusercontent.com/21675885/118628426-e1891180-b7cc-11eb-8cde-e3f43af2bb41.png)
Clicking on it leads me to a web page for confirmation, where the slot is now listed as **A**:
![Capture d’écran 2021-05-18 à 11 34 08](https://user-images.githubusercontent.com/21675885/118628561-01b8d080-b7cd-11eb-94dc-80594277d7b8.png)

Order then failed because the card was inserted in the wrong slot.

**Comment by rgaudin** [comment] 2021-05-18 09:37
Duplicate of #228

**Closed by rgaudin** 2021-05-18 09:37 UTC
Labels: bug

**Comment by rgaudin** [comment] 2021-05-18 09:55
The root cause is probably similar ; thanks for the report ; it's important we know how frequently that happens.

I am not convinced the slots were mixed up as there are only two scenarios leading to a (potential) change in slots assignation:
- reboot. Not the case, the machine has been up for 3months+
- SD card reader physically unplugged/plugged. As the machine is not easily reachable, I doubt it happened.

Not sure about why the message is mixed up but as for the failure, it seems that the reader for slot A currently hangs trying to enumerate the device. Maybe the SDcard inside (if there's one) has a problem or the reader itself or maybe this should be unplugged/repluged.
