### ISSUE TITLE
Failed creation for Order #5d97559c98c8bf0022a01fa3

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#138] opened 2019-10-04 14:33 UTC
Hotspot name is RDC_Fondation Orange : could the underscore be the issue?

Here is the log 
´´Starting to work on 5d97559d98c8bf0022a01fc8
updating task #5d97559d98c8bf0022a01fc8 status to: building
Starting image creation
Starting /usr/bin/kiwix-hotspot cli --root --filename 5d97559c98c8bf0022a01fa3 --build-dir /data --config /data/5d97559c98c8bf0022a01fa3.json --size 128GB

installer started: <subprocess.Popen object at 0x7f447bc961d0>
installer failed: 1
collecting full terminated log
installer rc: 1
Traceback (most recent call last):
  File "worker/tasks/create.py", line 103, in run
    getattr(self, method)()
  File "worker/tasks/create.py", line 188, in build_image
    raise subprocess.SubprocessError("installer rc: {}".format(ps.returncode))
subprocess.SubprocessError: installer rc: 1
updating task #5d97559d98c8bf0022a01fc8 status to: failed_to_build
job is not alive
job crashed: installer rc: 1´´

**Comment by rgaudin** [comment] 2019-10-04 14:38
Yes. I've probably said it already but whenever the error is in the creation step (`failed_to_build`), the relevant log is [the installer log](https://cardshop.hotspot.kiwix.org/all-orders/5d97559c98c8bf0022a01fa3/logs/create/installer.html).

When looking at it, it's clear that it fails very early due to `Invalid argument for `name`.`

I'm closing this as it's a duplicate of #83 then.

**Closed by rgaudin** 2019-10-04 14:38 UTC
Labels: bug

**Comment by Popolechien** [comment] 2019-10-04 14:39
ok good to know, thanks.

**Comment by rgaudin** [comment] 2019-10-04 14:40
I've pinned it so it gets fixed soon as this is getting frequent and affects users.
