### ISSUE TITLE
Error while ordering with `country` field left blank

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#151] opened 2020-03-12 09:52 UTC
Scenario: 
I ordered a configuration, but the address used only had a name and email (phone, address and country were left blank).
Got the following error message :
`Error while saving… NOT NULL constraint failed: manager_order.recipient_country_code`

Yet the order seemingly went through (which is fine), but clearly this shouldn't be flagged as an error (just like Address and Phone # are not).

**Comment by kelson42** [comment] 2021-04-21 22:04
Duplicate of #126

**Comment by rgaudin** [comment] 2021-04-22 08:58
Yes

**Closed by rgaudin** 2021-04-22 08:58 UTC
Labels: bug, duplicate, good first issue
