### ISSUE TITLE
Add "upload" button to Edupi field in Config>Content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#54] opened 2019-01-29 15:37 UTC
(based on user feedback)
Currently in the Configurations > content tab, "Edupi resources" is a text field asking for a ZIP archive. Shouldn't it be an upload button so that the Client can upload the content s/he wants Edupi with?

**Comment by rgaudin** [comment] 2019-01-29 16:11
I think this section is quite specific and requires more documentation/help as there are three use cases and none is clear/understood by users as Edupi is largely unknown.

* You have very few documents and a single hotspot: do nothing on the Cardshop and add your documents manually on your running hotspot.
* You have a small (size-wise) set of (potentially numerous) documents and/or multiple hotspots: uploading a small ZIP file (needs more instructions) make sense.
* You have a large (size-wise) number of documents (like WikiFundi which is ~1GB): upload is not practical and URL makes sense.

Those choices should be clearly explained. User should be able to understand that users will anyway be able to add files on running hotspot.

Maybe presets (like WikiFundi) should be selectable as well?

**Comment by kelson42** [comment] 2020-01-22 10:18
Duplicate of #106

**Closed by kelson42** 2020-01-22 10:18 UTC
Labels: enhancement
